# -*- coding: utf-8 -*-
"""Curva_ROC_revista.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWt9x83WiCWO21ERLdVGrdOy9oGOd42I
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.decomposition import PCA
from umap import UMAP
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_curve, roc_auc_score
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.naive_bayes import GaussianNB

# LOAD DATA
df = pd.read_csv("table.csv")

df['mood'] = df['mood'].map(lambda x: {0: "controle", 2: "TH", 3: "TH"}[x])
y = df['mood'] == 'TH'

def normalize_asv(X):
    return (X.T / X.sum(axis=1)).T

# PIPELINE FUNCTION

def run_model(model_name, use_sex):

    X = df.drop(['mood', 'id', 'sex'], axis=1)
    X = normalize_asv(X)

    if use_sex:
        X['sex'] = df['sex'] == 1

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    # PCA sempre (pros dois modeloqs)
    pca = PCA(n_components=0.99, random_state=42)
    X_train = pca.fit_transform(X_train)
    X_test = pca.transform(X_test)

    # UMAP apenas para HGB
    if model_name == "HGB":
        umap = UMAP(n_components=3, random_state=42)
        X_train = umap.fit_transform(X_train, y_train)
        X_test = umap.transform(X_test)
        model = HistGradientBoostingClassifier(random_state=42)
    else:
        model = GaussianNB()

    model.fit(X_train, y_train)

    y_proba = model.predict_proba(X_test)[:,1]
    fpr, tpr, _ = roc_curve(y_test, y_proba)
    auc = roc_auc_score(y_test, y_proba)

    return fpr, tpr, auc


# RUN MODELS

fpr_hgb_sex, tpr_hgb_sex, auc_hgb_sex = run_model("HGB", True)
fpr_hgb_nosex, tpr_hgb_nosex, auc_hgb_nosex = run_model("HGB", False)

fpr_gnb_sex, tpr_gnb_sex, auc_gnb_sex = run_model("GNB", True)
fpr_gnb_nosex, tpr_gnb_nosex, auc_gnb_nosex = run_model("GNB", False)

# SMOOTH CURVES

fpr_smooth = np.linspace(0,1,1000)

def smooth(fpr, tpr):
    return np.interp(fpr_smooth, fpr, tpr)

tpr_hgb_sex_s = smooth(fpr_hgb_sex, tpr_hgb_sex)
tpr_hgb_nosex_s = smooth(fpr_hgb_nosex, tpr_hgb_nosex)

tpr_gnb_sex_s = smooth(fpr_gnb_sex, tpr_gnb_sex)
tpr_gnb_nosex_s = smooth(fpr_gnb_nosex, tpr_gnb_nosex)

# FIGURE STYLE (JOURNAL)

plt.rcParams.update({
    "font.size": 10,
    "axes.linewidth": 1,
    "xtick.direction": "out",
    "ytick.direction": "out"
})

fig, axes = plt.subplots(2, 1, figsize=(6, 10))


# A – HGB

axes[0].plot(fpr_smooth, tpr_hgb_sex_s,
             color='black',
             linewidth=2,
             label=f'With Sex (AUC = {auc_hgb_sex:.3f})')

axes[0].plot(fpr_smooth, tpr_hgb_nosex_s,
             color='black',
             linestyle='--',
             linewidth=2,
             label=f'No Sex (AUC = {auc_hgb_nosex:.3f})')

axes[0].plot([0,1],[0,1],
             linestyle=':',
             color='gray',
             linewidth=1)

axes[0].set_xlim(0,1)
axes[0].set_ylim(0,1)
axes[0].set_aspect('equal', adjustable='box')

axes[0].set_xlabel("False Positive Rate")
axes[0].set_ylabel("True Positive Rate")

# remove bordas superiores e direitas
axes[0].spines['top'].set_visible(False)
axes[0].spines['right'].set_visible(False)

axes[0].legend(loc='center left',
               bbox_to_anchor=(1.02, 0.5),
               frameon=False)

axes[0].text(-0.15, 1.05, "A",
             transform=axes[0].transAxes,
             fontsize=14,
             fontweight='bold')


# PANEL B – GNB

axes[1].plot(fpr_smooth, tpr_gnb_sex_s,
             color='black',
             linewidth=2,
             label=f'With Sex (AUC = {auc_gnb_sex:.3f})')

axes[1].plot(fpr_smooth, tpr_gnb_nosex_s,
             color='black',
             linestyle='--',
             linewidth=2,
             label=f'No Sex (AUC = {auc_gnb_nosex:.3f})')

axes[1].plot([0,1],[0,1],
             linestyle=':',
             color='gray',
             linewidth=1)

axes[1].set_xlim(0,1)
axes[1].set_ylim(0,1)
axes[1].set_aspect('equal', adjustable='box')

axes[1].set_xlabel("False Positive Rate")
axes[1].set_ylabel("True Positive Rate")

axes[1].spines['top'].set_visible(False)
axes[1].spines['right'].set_visible(False)

axes[1].legend(loc='center left',
               bbox_to_anchor=(1.02, 0.5),
               frameon=False)

axes[1].text(-0.15, 1.05, "B",
             transform=axes[1].transAxes,
             fontsize=14,
             fontweight='bold')


plt.subplots_adjust(hspace=0.45, right=0.75)

plt.savefig("Figure1_ROC.pdf",
            format="pdf",
            dpi=600,
            bbox_inches="tight")

plt.show()

print("Figure saved as Figure1_ROC.pdf")